backend: 
  name: git-gateway

media_folder: content/files/
public_folder: /files/csv

collections:
  - name: "csv"
    label: Import CSV file
    folder: content/files/csv
    create: true
    title: csv
    slug: file.csv
    fields:
      - { label: "Title", name: "title", default: "CSV File", widget: "hidden" }
      - { label: "File", name: "file", widget: "file" }