backend: 
  name: git-gateway

media_folder: content/uploads/
public_folder: /files/uploads

collections:
  - label: "CSV File"
    name: "csv"
    files: 
      - label: "CSV"
        name: "csv"
        file: content/files/index.json
        slug: "index.csv"
        fields: 
          - label: CSV File
            name: csv
            widget: file